[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.env]]
key = "NODE_ENV"
value = "production"

[[deploy.env]]
key = "PORT"
value = "3000"